# Generated by Django 2.2.3 on 2019-09-02 13:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFloors',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('altitude', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('floor_number', models.IntegerField()),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('organization_name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, choices=[('Owner', 'Owner')], max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.CharField(blank=True, max_length=60, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization-images')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pro_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('who_can_join', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=70, null=True)),
                ('is_dispatch', models.BooleanField(default=False)),
                ('is_alert_sams', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('number_of_floors', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('name', models.CharField(max_length=50)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='ZoneCCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='zone/documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneFloor',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('cctv_camera', models.ManyToManyField(blank=True, to='organization.ZoneCCTV')),
                ('document', models.ManyToManyField(blank=True, to='organization.ZoneDocument')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationFloors')),
                ('organization_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Zone')),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationType'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='organization.OrganizationProfile'),
        ),
        migrations.CreateModel(
            name='OrganizationGeoFence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('co_ordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile')),
            ],
        ),
        migrations.AddField(
            model_name='organizationfloors',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile'),
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('name', models.CharField(max_length=50)),
                ('contact_role', models.CharField(choices=[('Owner', 'Owner')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_manually_added', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile')),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Wife', 'Wife'), ('Husband', 'Husband'), ('Family Member', 'Family Member'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('uuid', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
    ]
