# Generated by Django 2.2.3 on 2019-09-18 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_emergencycontact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcontact',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
