# Generated by Django 2.2.3 on 2019-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
