# Generated by Django 2.2.3 on 2019-09-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190920_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='organizationcontact',
            name='is_joined',
        ),
    ]
