# Generated by Django 2.2.3 on 2019-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190920_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='altitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='altitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
