# Generated by Django 2.2.3 on 2019-12-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='shinobi_authkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='shinobi_group_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
