# Generated by Django 2.2.3 on 2019-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20191220_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecctv',
            name='monitor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
