# Generated by Django 2.2.3 on 2020-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20200114_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='request_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
