# Generated by Django 2.2.3 on 2020-06-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_emergencycontact_request_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontact',
            old_name='request_checkin',
            new_name='request_checkin_updated',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='request_checkin_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='request_checkin_latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='request_checkin_longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
