# Generated by Django 2.2.3 on 2020-06-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20200618_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, upload_to='static/media/', verbose_name='organization file')),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageorganization', to='organization.OrganizationProfile')),
            ],
        ),
    ]
