# Generated by Django 2.2.3 on 2020-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_organizationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
