# Generated by Django 2.2.3 on 2021-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_userorganization_is_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='is_covid_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='is_show_covid_info',
            field=models.BooleanField(default=False),
        ),
    ]
