# Generated by Django 2.2.3 on 2019-10-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='battery_power',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
