# Generated by Django 2.2.3 on 2021-05-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210407_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_covid_status_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
