# Generated by Django 2.2.3 on 2021-05-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_covid_status_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_covid_status_hidden',
        ),
    ]
