# Generated by Django 2.2.3 on 2021-04-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('latitude', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.CharField(blank=True, max_length=60, null=True)),
                ('is_infected', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('place_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_tagging', to='contacts.UserContacts')),
            ],
        ),
    ]
