# Generated by Django 2.2.3 on 2021-04-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastupdated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Last Updated',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='AssistanceLocationsReview',
            fields=[
            ],
            options={
                'verbose_name': 'Assistance Locations',
                'verbose_name_plural': 'Assistance Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('location.assistancelocations',),
        ),
        migrations.CreateModel(
            name='DiseaseReview',
            fields=[
            ],
            options={
                'verbose_name': 'disease',
                'verbose_name_plural': 'diseases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.disease',),
        ),
        migrations.CreateModel(
            name='DoseReview',
            fields=[
            ],
            options={
                'verbose_name': 'dose',
                'verbose_name_plural': 'doses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vaccines.dose',),
        ),
        migrations.CreateModel(
            name='FlightDetailsReview',
            fields=[
            ],
            options={
                'verbose_name': 'Flight Details',
                'verbose_name_plural': 'Flight Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flight.flightdetails',),
        ),
        migrations.CreateModel(
            name='FlightReview',
            fields=[
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flight.flight',),
        ),
        migrations.CreateModel(
            name='GlobalLocationsReview',
            fields=[
            ],
            options={
                'verbose_name': 'Global Locations',
                'verbose_name_plural': 'Global Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('location.globallocations',),
        ),
        migrations.CreateModel(
            name='ManufacturerReview',
            fields=[
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'manufacturers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vaccines.manufacturer',),
        ),
        migrations.CreateModel(
            name='QuestionsReview',
            fields=[
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flight.questions',),
        ),
        migrations.CreateModel(
            name='SymptomsReview',
            fields=[
            ],
            options={
                'verbose_name': 'Symptoms',
                'verbose_name_plural': 'Symptoms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.symptoms',),
        ),
        migrations.CreateModel(
            name='UserAnswersReview',
            fields=[
            ],
            options={
                'verbose_name': 'User Answers',
                'verbose_name_plural': 'User Answers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flight.useranswers',),
        ),
        migrations.CreateModel(
            name='UserContactsReview',
            fields=[
            ],
            options={
                'verbose_name': 'User Contacts',
                'verbose_name_plural': 'User Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.usercontacts',),
        ),
        migrations.CreateModel(
            name='UserLocationsReview',
            fields=[
            ],
            options={
                'verbose_name': 'User Locations',
                'verbose_name_plural': 'User Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('location.userlocations',),
        ),
        migrations.CreateModel(
            name='UserVaccineReview',
            fields=[
            ],
            options={
                'verbose_name': 'User Vaccines',
                'verbose_name_plural': 'User Vaccines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vaccines.uservaccine',),
        ),
        migrations.CreateModel(
            name='UserTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('tested_date', models.DateField()),
                ('test_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], default='Negative', max_length=20)),
                ('file_upload', models.FileField(blank=True, upload_to='static/media/', verbose_name='testing file')),
                ('is_reminded', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_testing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Testings',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_date', models.DateField(blank=True, null=True)),
                ('data_started', models.DateField(blank=True, null=True)),
                ('is_tested', models.BooleanField(default=False)),
                ('test_result', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], default='Negative', max_length=20)),
                ('current_status', models.CharField(blank=True, choices=[('Actively Experiencing Symptoms', 'Actively Experiencing Symptoms'), ('Actively Not Experiencing Symptoms', 'Actively Not Experiencing Symptoms')], default='Actively Not Experiencing Symptoms', max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_disease', to='contacts.Disease')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_status', to='covid_accounts.Status')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='user_symptoms', to='contacts.Symptoms')),
                ('testing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_testing', to='covid_accounts.UserTesting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_vaccine', to='vaccines.UserVaccine')),
            ],
            options={
                'verbose_name_plural': 'User Reports',
            },
        ),
    ]
