# Generated by Django 2.2.3 on 2021-08-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'screening',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ScreeningUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'Everything is OK'), ('Need test', 'test should be done')], max_length=100)),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='covid_accounts.Screening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'screening_user',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('multiple', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='covid_accounts.Screening')),
            ],
            options={
                'db_table': 'screening_question',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_symptom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='covid_accounts.ScreeningQuestion')),
            ],
            options={
                'db_table': 'screening_option',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('screening_answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_answer', to='covid_accounts.ScreeningAnswerOption')),
                ('screening_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_answer', to='covid_accounts.ScreeningUser')),
            ],
            options={
                'db_table': 'screening_answer',
                'ordering': ('id',),
            },
        ),
    ]
