# Generated by Django 2.2.3 on 2021-08-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_accounts', '0002_screening_screeninganswer_screeningansweroption_screeningquestion_screeninguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='covid_accounts.ScreeningQuestion'),
        ),
    ]
