# Generated by Django 2.2.3 on 2021-04-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Province_State', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('County', models.CharField(blank=True, max_length=255, null=True)),
                ('Country_Region', models.CharField(blank=True, max_length=255, null=True)),
                ('Last_Update', models.DateTimeField(blank=True, null=True)),
                ('Lat', models.CharField(blank=True, max_length=100, null=True)),
                ('Long', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirmed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Deaths', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Recovered', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Active', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('Country_Region', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Province_State', models.CharField(blank=True, max_length=255, null=True)),
                ('location_date', models.DateField()),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_infected', models.BooleanField(default=False)),
                ('place_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocationTagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('is_infected', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location_tagging', to='location.UserLocations')),
            ],
        ),
        migrations.CreateModel(
            name='AssistanceLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Country_Region', models.CharField(blank=True, max_length=255, null=True)),
                ('Province_State', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, choices=[('Food Aid', 'Food Aid'), ('Supplies', 'Supplies'), ('Financial Help', 'Financial Help'), ('Test Center', 'Test Center'), ('Vaccine', 'Vaccine')], default='Food Aid', max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Giveaway', 'Giveaway'), ('Assistance', 'Assistance')], default='Giveaway', max_length=100, null=True)),
                ('dispaly_location', models.CharField(blank=True, choices=[('2 weeks', '2 weeks'), ('3 weeks', '3 weeks'), ('4 weeks', '4 weeks'), ('5 weeks', '5 weeks'), ('6 weeks', '6 weeks'), ('7 weeks', '7 weeks'), ('8 weeks', '8 weeks')], default='2 weeks', max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('to_date', models.DateField()),
                ('from_date', models.DateField()),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('permanent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assistance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
