# Generated by Django 2.2.3 on 2021-04-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vaccines.Dose')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('validity_period', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_disease', to='contacts.Disease')),
                ('requirement_dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_dose', to='vaccines.Dose')),
            ],
        ),
        migrations.CreateModel(
            name='UserVaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('vaccinated_date', models.DateField()),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('file_upload', models.FileField(blank=True, upload_to='static/media/', verbose_name='vaccination file')),
                ('is_reminded', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_dose', to='vaccines.Dose')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_manufacturer', to='vaccines.Manufacturer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vaccine', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
