from django.urls import path

from .views import (
    UserCreateAPIView,
    UserLoginAPIView,
    UserListAPIView,
    UserUpdateAPIView,
    UserDetailAPIView,
    UserActivationAPIView,
    IsEmailExistsAPIView,
    ResetPasswordAPIView,
    SendMobileNumberOTPAPIView,
    VerifyMobileOTPAPIView,
    ResendUserActivationAPIView,
    CustomResetPasswordConfirm,
    CustomResetPasswordRequestToken,
    AddProfilePicAPIView,
    UserResetPasswordAPIView,
    FCMDeviceCreateAPIView,
    MobileForgotPasswordAPIView,
    MobileForgotPasswordVerifyAPIView,
    MobileResetPasswordAPIView,
    EmergencyContactAddView,
    EmergencyContactListAPIView,
    EmergencyContactActivateAPIView,
    EmergencyContactDeleteAPIView,
    EmergencyContactDetailsListAPIView,
    UserPhoneListAPIView,
    EmergencyContactCheckinAPIView,
    ContactLocationUpdateAPIView,
    FCMUpdateAPIView, UserUpdateProfileAPIView, UserDetailListAPIView, UserNotificationsAPIView,
    UserNotificationUpdateAPIView, CurrentLocationAPIView, ShareLocationAPIView, UserSettingsAPIView,
    UserSettingsUpdateAPIView, ListNotificationAPIView, DeleteNotificationAPIView, GeoFenceListCreateAPIView,
    UpdateGeoFenceDetails, DeleteGeoFenceDetails, ListManagingGeoFences, ListAssignedGeoFences,
    UserGeofenceStatusActivateAPIView, HideGeofenceAPIView, SendGeofenceNotificationAPIView,
    LeaveGeofenceAssignedUserAPIView, HidemodeCheckinGeofenceAPIView
)

urlpatterns = [
    path('', UserListAPIView.as_view(), name='list'),
    path('register/', UserCreateAPIView.as_view(), name='register'),
    path('list-users/', UserPhoneListAPIView.as_view(), name='list-user'),
    path('user-notifications/', UserNotificationsAPIView.as_view(), name='user-notifications'),
    path('user-settings/', UserSettingsAPIView.as_view(), name='user-settings'),
    path('user-details/', UserDetailListAPIView.as_view(), name='user-details'),
    path('login/', UserLoginAPIView.as_view(), name='login'),
    path('update-profile/', UserUpdateProfileAPIView.as_view(), name='update-profile'),
    path('update-notification-settings/', UserNotificationUpdateAPIView.as_view(), name='update-notification-settings'),
    path('update-user-settings/', UserSettingsUpdateAPIView.as_view(), name='update-user-settings'),
    path('<int:pk>/update/', UserUpdateAPIView.as_view(), name='update'),
    path('<int:pk>/detail/', UserDetailAPIView.as_view(), name='detail'),
    path('is-email-exists/', IsEmailExistsAPIView.as_view(), name='check-email'),
    path('reset-password/', ResetPasswordAPIView.as_view(), name='reset-password'),
    path('account-activation/', UserActivationAPIView.as_view(), name='user_activation'),
    path('resend-account-activation/', ResendUserActivationAPIView.as_view(), name='resend_user_activation'),
    path('sent-otp/', SendMobileNumberOTPAPIView.as_view(), name='sent-otp'),
    path('verify-otp/', VerifyMobileOTPAPIView.as_view(), name='verify-otp'),
    path('forgot-password/confirm/', CustomResetPasswordConfirm.as_view(), name="reset-password-confirm"),
    path('forgot-password/', CustomResetPasswordRequestToken.as_view(), name="reset-password-request"),
    path('update-profile-picture/', AddProfilePicAPIView.as_view(), name="update-profile-picture"),
    path('user-profile-reset-password/', UserResetPasswordAPIView.as_view(), name='user-profile-reset-password'),
    path('add-fcm-token/', FCMDeviceCreateAPIView.as_view(), name='add-fcm-token'),
    path('update-fcm-token/<int:pk>/', FCMUpdateAPIView.as_view(), name='update-fcm-token'),
    path('mobile-forgot-password/', MobileForgotPasswordAPIView.as_view(), name='mobile-forgot-password'),
    path('mobile-forgot-password-verify-otp/', MobileForgotPasswordVerifyAPIView.as_view(),
         name='mobile-forgot-password-verify-otp'),
    path('mobile-forgot-password-update/', MobileResetPasswordAPIView.as_view(), name='mobile-forgot-password-update'),

    # Emergency Contacts
    path('emergency-contact/', EmergencyContactAddView.as_view(), name='emergency-contact'),
    path('contact-location-update/', ContactLocationUpdateAPIView.as_view(), name='contact-location-update'),
    path('emergency-contact-list/', EmergencyContactListAPIView.as_view(), name='emergency-contact-list'),
    path('emergency-contact-activate/', EmergencyContactActivateAPIView.as_view(), name='emergency-contact-activate'),
    path('user-contact-delete/<int:pk>/', EmergencyContactDeleteAPIView.as_view(), name='contact-delete'),
    path('get-user-contacts/', EmergencyContactDetailsListAPIView.as_view(), name='contact-details'),
    # Share location
    path('contact-request-check-in/', EmergencyContactCheckinAPIView.as_view(), name='contact-request-check-in'),
    path('current-location-update/', CurrentLocationAPIView.as_view(), name='current-location-update'),
    path('share-my-location-update/', ShareLocationAPIView.as_view(), name='share-location-update'),
    path('list-notifications/', ListNotificationAPIView.as_view(), name='list-notification-view'),
    path('<int:notification_id>/delete-notification/', DeleteNotificationAPIView.as_view(), name='delete-notification-view'),

    # Geo Fence
    path('add-geofence/', GeoFenceListCreateAPIView.as_view(), name='add-geofence'),
    path('update-geofence/<int:geofence_id>/', UpdateGeoFenceDetails.as_view(), name='update-geofence'),
    path('delete-geofence/<int:geofence_id>/', DeleteGeoFenceDetails.as_view(), name='delete-geofence'),
    path('geofence-contact-activate/', UserGeofenceStatusActivateAPIView.as_view(), name='geofence-contact-activate'),
    path('list-managing-geofence/', ListManagingGeoFences.as_view(), name='list-managing-geofence'),
    path('list-assigned-geofence/', ListAssignedGeoFences.as_view(), name='list-assigned-geofence'),
    path('hide-geofence/<int:geofence_id>/<str:type>/', HideGeofenceAPIView.as_view(), name='hide-geofence'),
    path('send-geofence-notification/', SendGeofenceNotificationAPIView.as_view(), name='send-geofence-notification'),
    path('leave-geofence-user/<int:geofence_id>/<str:type>/', LeaveGeofenceAssignedUserAPIView.as_view(), name='leave-geofence-user'),
    path('hidemode-checkin-geofence/', HidemodeCheckinGeofenceAPIView.as_view(), name='hidemode-checkin-geofence'),
]
