from django.urls import path
from .views import (
    IncidentListCreateAPIView,
    IncidentRetrieveUpdateDeleteAPIView,
    IncidentLocationAPIView,
    EmergencyQuickContactAddAPIView,
    IncidentRespondersAlertAPIView,
    RespondersListAPIView,
    EndOfIncidentAPIView,
    ResponderLocationUpdateAPIView,
    JoinedRespondersListAPIView,
    IncidentRetrieveAPIView,
    OrganizersListApiView,
    GetIncidentParamsAPIView,
    IncidentCheckoutAPIView,
    ReporterLocationTrackingAPIView,
    GetOrganizationZoneFloorAPIView,
    GetResponderStreamAPIView,
    GetJoinedResponderByStreamIdAPIView,
    antmedia_webhook,
    IncidentHistoryListAPIView,
    OngoingIncidentListAPIView,
    IncidentContactsShareAPIView,
    IncidentOrganizationShareAPIView
)

urlpatterns = [
    path('list-create/', IncidentListCreateAPIView.as_view(), name='create-list-incident'),
    path('<int:pk>/incident/', IncidentRetrieveUpdateDeleteAPIView.as_view(), name='incident-update-retrieve-delete'),
    path('incident-location/', IncidentLocationAPIView.as_view(), name='incident-location'),
    path('emergency-quick-contact/', EmergencyQuickContactAddAPIView.as_view(), name='emergency-quick-contact'),
    path('send-incident-alert-notifications/', IncidentRespondersAlertAPIView.as_view(),
         name='send-incident-alert-notifications'),
    path('responders-list/', RespondersListAPIView.as_view(), name='responders-list'),
    path('end-of-incident/', EndOfIncidentAPIView.as_view(), name='end-of-incident'),
    path('responder-location-update/', ResponderLocationUpdateAPIView.as_view(), name='responder-location-update'),
    path('joined-responders-list/', JoinedRespondersListAPIView.as_view(), name='joined-responders-list'),
    path('<int:pk>/incident-retrieve/', IncidentRetrieveAPIView.as_view(), name='incident-retrieve'),
    path('organizers-list/', OrganizersListApiView.as_view(), name='organizers-list'),
    path('incident-params/', GetIncidentParamsAPIView.as_view(), name='incident-params'),
    path('incident-checkout/', IncidentCheckoutAPIView.as_view(), name='incident-checkout'),
    path('reporter-locations/<int:pk>/', ReporterLocationTrackingAPIView.as_view(), name='reporter-locations'),
    path('responder-streams/<int:pk>/', GetResponderStreamAPIView.as_view(), name='responder-streams'),
    path('get-organization-zone-floor/', GetOrganizationZoneFloorAPIView.as_view(), name='get-organization-zone-floor'),
    path('get-responder-by-stream-id/', GetJoinedResponderByStreamIdAPIView.as_view(), name='get-responder-by-stream-id'),
    path('ant-media-webhooks/', antmedia_webhook, name='antmedia-webhook'),
    path('incident-history/', IncidentHistoryListAPIView.as_view(), name='incident-history'),
    path('ongoing-incident/', OngoingIncidentListAPIView.as_view(), name='ongoing-incident'),
    path('incident-contacts-sharing/', IncidentContactsShareAPIView.as_view(), name='incident-contacts-sharing'),
    path('incident-organization-sharing/', IncidentOrganizationShareAPIView.as_view(), name='incident-organization-sharing'),
]
