# Generated by Django 2.2.3 on 2019-09-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
