# Generated by Django 2.2.3 on 2019-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='wowza_streaming_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
