# Generated by Django 2.2.3 on 2019-09-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
        ('accounts', '0001_initial'),
        ('incident', '0003_incident_wowza_streaming_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IncidentJoinedResponder',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('is_joined', models.BooleanField(default=False)),
                ('emergency_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_emergency_contact', to='organization.EmergencyContact')),
                ('organization_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_organization_contact', to='organization.OrganizationContact')),
                ('user_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_incident', to='incident.Incident')),
            ],
            bases=('accounts.timestampedmodel',),
        ),
    ]
