# Generated by Django 2.2.3 on 2019-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
        ('incident', '0004_auto_20190920_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentjoinedresponder',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='incidentjoinedresponder',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='emergency_contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_emergency_contact', to='organization.EmergencyContact'),
        ),
        migrations.RemoveField(
            model_name='incidentjoinedresponder',
            name='organization_contact',
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='organization_contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_organization_contact', to='organization.OrganizationContact'),
        ),
    ]
