# Generated by Django 2.2.3 on 2019-10-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('incident', '0005_auto_20190923_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentUrlTracker',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('key', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=200)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
    ]
