# Generated by Django 2.2.3 on 2019-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_incidenturltracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenturltracker',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
