# Generated by Django 2.2.3 on 2019-10-16 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_battery_power'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incident', '0007_auto_20191004_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterLocationTracker',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('altitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reporter_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_incident', to='incident.Incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('accounts.timestampedmodel',),
        ),
    ]
