# Generated by Django 2.2.3 on 2019-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_reporterlocationtracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='wowza_streaming_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='room_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='streaming_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
