# Generated by Django 2.2.3 on 2019-11-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
        ('incident', '0009_auto_20191118_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='stream_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='incidentjoinedresponder',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='emergency_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_emergency_contact', to='organization.EmergencyContact'),
        ),
        migrations.RemoveField(
            model_name='incidentjoinedresponder',
            name='organization_contact',
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='organization_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_organization_contact', to='organization.OrganizationContact'),
        ),
    ]
