# Generated by Django 2.2.3 on 2019-12-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_auto_20191122_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='vod_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='vod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidentjoinedresponder',
            name='vod_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
