# Generated by Django 2.2.3 on 2019-12-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0011_auto_20191212_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='stream_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
