# Generated by Django 2.2.3 on 2019-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0012_incident_stream_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
