# Generated by Django 2.2.3 on 2019-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0013_incident_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='preview_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='incident-images'),
        ),
    ]
