# Generated by Django 2.2.3 on 2019-12-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0014_incident_preview_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='preview_thumbnail',
            new_name='stream_thumbnail',
        ),
    ]
