# Generated by Django 2.2.3 on 2020-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0015_auto_20191226_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='stream_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
