# Generated by Django 2.2.3 on 2020-11-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0016_incident_stream_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='stream_start_time',
        ),
    ]
