# Generated by Django 2.2.3 on 2019-11-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReporterType',
            new_name='ReportType',
        ),
    ]
