# Generated by Django 2.2.3 on 2019-11-20 13:45

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191120_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='organization.OrganizationProfile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='send_anonymously',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
