# Generated by Django 2.2.3 on 2019-11-22 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_battery_power'),
        ('reports', '0005_auto_20191120_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFiles',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('file_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            bases=('accounts.timestampedmodel',),
        ),
    ]
