# Generated by Django 2.2.3 on 2019-11-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfiles',
            name='file',
            field=models.FileField(null=True, upload_to='report_files/', verbose_name=''),
        ),
    ]
