# Generated by Django 2.2.3 on 2019-11-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20191122_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfiles',
            name='file',
            field=models.FileField(upload_to='report_files/'),
        ),
    ]
