# Generated by Django 2.2.3 on 2019-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20191122_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfiles',
            name='file_report',
        ),
        migrations.AddField(
            model_name='report',
            name='files',
            field=models.ManyToManyField(to='reports.ReportFiles'),
        ),
    ]
