# Generated by Django 2.2.3 on 2019-11-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20191122_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='files',
        ),
    ]
