# Generated by Django 2.2.3 on 2019-11-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_battery_power'),
        ('reports', '0012_reportfiles_file_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.TimeStampedModel')),
                ('file', models.FileField(upload_to='report_files/')),
                ('file_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            bases=('accounts.timestampedmodel',),
        ),
        migrations.DeleteModel(
            name='ReportFiles',
        ),
    ]
