# Generated by Django 2.2.3 on 2019-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
        ('reports', '0013_auto_20191126_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='organization',
        ),
        migrations.AddField(
            model_name='report',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='organization.OrganizationProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='zone_floors',
            field=models.ManyToManyField(blank=True, to='organization.ZoneFloor'),
        ),
        migrations.AddField(
            model_name='report',
            name='zones',
            field=models.ManyToManyField(blank=True, to='organization.Zone'),
        ),
    ]
