# Generated by Django 2.2.3 on 2019-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20191126_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='maintenance_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
