# Generated by Django 2.2.3 on 2019-11-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190920_1116'),
        ('reports', '0016_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='zone_floors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='zones',
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationProfile'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Zone'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_zone_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.ZoneFloor'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporting_organizations',
            field=models.ManyToManyField(blank=True, related_name='organization_reports', to='organization.OrganizationProfile'),
        ),
    ]
