# Generated by Django 2.2.3 on 2019-12-12 06:52

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20191127_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(upload_to=apps.reports.models.report_directory_path),
        ),
    ]
