# Generated by Django 2.2.3 on 2020-06-03 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0018_auto_20191212_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_message', models.BooleanField(blank=True, default=True, null=True)),
                ('contact_request', models.BooleanField(blank=True, default=True, null=True)),
                ('contact_disable_location', models.BooleanField(blank=True, default=True, null=True)),
                ('crisis_emergency_alert', models.BooleanField(blank=True, default=True, null=True)),
                ('contact_has_incident', models.BooleanField(blank=True, default=True, null=True)),
                ('send_incident_text', models.BooleanField(blank=True, default=True, null=True)),
                ('send_incident_email', models.BooleanField(blank=True, default=True, null=True)),
                ('app_tips', models.BooleanField(blank=True, default=True, null=True)),
                ('new_updates', models.BooleanField(blank=True, default=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
