# Generated by Django 2.2.3 on 2020-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='app_tips',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='contact_has_incident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='contact_request',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
