# Generated by Django 2.2.3 on 2020-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20200605_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='auto_route_contacts',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='auto_route_incident_organization',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='bluetooth',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='nfc',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='shake_activate_incident',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='siri_incident_start',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
