# Generated by Django 2.2.3 on 2020-06-23 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_notificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='array_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
