# Generated by Django 2.2.3 on 2020-06-23 11:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_notificationhistory_array_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
