# Generated by Django 2.2.3 on 2020-07-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0026_geogroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeofences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_checkin', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_contacts', models.ManyToManyField(blank=True, related_name='geofencecontacts', to=settings.AUTH_USER_MODEL)),
                ('assign_mangers', models.ManyToManyField(blank=True, related_name='geofencemanager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofenceuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GeoGroups',
        ),
    ]
