# Generated by Django 2.2.3 on 2020-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_auto_20200713_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeofences',
            name='assign_contacts',
            field=models.ManyToManyField(blank=True, related_name='geofencecontacts', to='organization.EmergencyContact'),
        ),
        migrations.AlterField(
            model_name='usergeofences',
            name='assign_mangers',
            field=models.ManyToManyField(blank=True, related_name='geofencemanager', to='organization.EmergencyContact'),
        ),
    ]
