# Generated by Django 2.2.3 on 2020-07-16 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_userorganization_is_muted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0028_auto_20200713_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeofences',
            name='auto_checkin',
        ),
        migrations.CreateModel(
            name='UserGeofenceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('contact_type', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Contact', 'Contact')], max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedemergency', to='organization.EmergencyContact')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedgeofence', to='reports.UserGeofences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedgeofenceuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
