# Generated by Django 2.2.3 on 2020-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20200721_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeofences',
            name='request_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
