# Generated by Django 2.2.3 on 2020-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_usergeofences_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeofences',
            name='request_status',
        ),
        migrations.AddField(
            model_name='usergeofencestatus',
            name='request_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
