# Generated by Django 2.2.3 on 2020-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_auto_20200824_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeofences',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usergeofences',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
