# Generated by Django 2.2.3 on 2021-04-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_auto_20200916_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='exposed_locations',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='infected_contact',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='traced_exposure',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='send_incident_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
